services:
    app:
        image: noeldemartin/noeldemartin.com
        volumes:
            - ./database/database.sqlite:/app/database/database.sqlite
            - ./storage:/app/storage
            - ./.env:/app/.env
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - noeldemartin

networks:
    default:
        name: nginx-agora
        external: true
