<?php

return [
    'title' => 'Podcast',
    'content' => <<<END
        Wait, do I have a podcast now!?

        Actually, no 😅. I just generated and episode once using [NotebookLM](https://notebooklm.google.com/),
        and I decided to go through all the trouble of setting up [a feed](/podcast/feed.xml) to see how hard could
        it be. Turns out, it wasn't too hard!
        END,
    'episodes' => [
        [
            'title' => 'Umai Development Journal (by NotebookLM)',
            'filename' => '00-umai-development-journal-by-notebooklm.mp3',
            'filelength' => '25590229',
            'duration' => '1065',
            'content' => <<<END
                Episode generated by [NotebookLM](https://notebooklm.google.com/) from [my development journal](https://noeldemartin.com/tasks/implementing-a-recipes-manager-using-solid).

                Notes:
                    - Check out the live version of [Umai](https://umai.noeldemartin.com).
                    - Learn more about the [Shape Up](https://basecamp.com/shapeup) methodology.
                    - You can implement an app like Umai using [Aerogel](https://aerogel.js.org/).
                    - I gave a presentation at [FOSDEM](https://noeldemartin.com/fosdem) sharing my work on Umai and other Solid Apps.
                END,
        ],
    ],
];
