title: Project
tabs:
  main:
    display: Main
    sections:
      - fields:
          - handle: title
            field:
              type: text
              required: true
              validate:
                - required
              width: 33
          - handle: link
            field:
              type: link
              display: Link
              width: 66
          - handle: logo
            field:
              type: text
              display: Logo
              width: 33
          - handle: logo_classes
            field:
              type: text
              display: 'Logo classes'
              width: 66
          - handle: content
            field:
              type: markdown
              display: Description
              antlers: true
  sidebar:
    display: Sidebar
    sections:
      - fields:
          - handle: category
            field:
              options:
                - key: app
                  value: App
                - key: tool
                  value: 'Developer Tool'
                - key: discontinued
                  value: Discontinued
              type: select
              display: Category
              validate:
                - required
          - handle: state
            field:
              options:
                - key: live
                  value: Live
                - key: wip
                  value: WIP
                - key: experimental
                  value: Experimental
                - key: archived
                  value: Archived
              type: select
              display: State
              validate:
                - required
          - handle: platform
            field:
              type: text
              display: Platform
  page:
    display: Page
    sections:
      - fields:
          - handle: team
            field:
              type: replicator
              display: Team
              sets:
                team_members:
                  display: ''
                  sets:
                    team_member:
                      display: 'Team member'
                      fields:
                        - handle: name
                          field:
                            type: text
                            display: Name
                        - handle: avatar
                          field:
                            type: text
                            display: Avatar
                        - handle: link
                          field:
                            type: link
                            display: Link
                        - handle: role
                          field:
                            type: text
                            display: Role
