<?php echo '<?xml version="1.0" encoding="utf-8" ?>' . "\n"; ?>
<?php echo '<?xml-stylesheet type="text/xsl" href="' . route('podcast.xsl') . '" ?>' . "\n"; ?>
<rss xmlns:podcast="https://podcastindex.org/namespace/1.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" xml:lang="en" version="2.0">
    <channel>
        <title>Noel De Martin</title>
        <description>I don't really have a podcast, but I published an episode once generated with NotebookLM.</description>
        <link>{{ sroute('podcast') }}</link>
        <atom:link href="{{ route('podcast.feed') }}" rel="self" type="application/rss+xml"/>
        <lastBuildDate>Fri Nov 08 2024 11:18:48 GMT+0700</lastBuildDate>
        <language>en-us</language>
        <itunes:image href="{{ asset('img/myface.png') }}" />
        <podcast:guid>8651f507-c9eb-518b-a4dc-19296559426f</podcast:guid>
        <image>
            <url>{{ asset('img/myface.png') }}</url>
            <title>Noel De Martin</title>
            <link>{{ sroute('podcast') }}</link>
        </image>
        <itunes:author>Noel De Martin</itunes:author>
        <itunes:owner>
            <itunes:name>Noel De Martin</itunes:name>
        </itunes:owner>
        <itunes:explicit>false</itunes:explicit>
        <podcast:medium>podcast</podcast:medium>
        <item>
            <title>Umai Development Journal (by NotebookLM)</title>
            <itunes:title>Umai Development Journal (by NotebookLM)</itunes:title>
            <description><![CDATA[<p>Episode generated by <a href="https://notebooklm.google.com/" target="_blank">NotebookLM</a> from <a href="https://noeldemartin.com/tasks/implementing-a-recipes-manager-using-solid" target="_blank">my development journal</a>.</p><p>Notes:</p><ul><li>Check out the live version of <a href="https://umai.noeldemartin.com" target="_blank">Umai</a>.</li><li>Learn more about the <a href="https://basecamp.com/shapeup" target="_blank">Shape Up</a> methodology.</li><li>You can implement an app like Umai using <a href="https://aerogel.js.org/" target="_blank">Aerogel</a>.</li><li>I gave a presentation at <a href="https://noeldemartin.com/fosdem" target="_blank">FOSDEM</a> sharing my work on Umai and other Solid Apps.</li></ul>]]></description>
            <link>{{ sroute('podcast') }}</link>
            <enclosure url="{{ url('/downloads/podcast/00-umai-development-journal-by-notebooklm.mp3') }}" length="25590229" type="audio/mpeg"/>
            <guid>{{ url('/downloads/podcast/00-umai-development-journal-by-notebooklm.mp3') }}</guid>
            <itunes:duration>1065</itunes:duration>
            <itunes:episodeType>full</itunes:episodeType>
            <itunes:episode>0</itunes:episode>
            <podcast:episode>0</podcast:episode>
            <itunes:explicit>false</itunes:explicit>
            <pubDate>Fri Nov 08 2024 11:18:48 GMT+0700</pubDate>
            <itunes:image href="{{ asset('img/myface.png') }}"/>
        </item>
    </channel>
</rss>
